config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #root 'messages#index'
  #root 'devise/sessions#new'
  #root :to => redirect("/users/sign_in")
  # get 'login', to: 'users#index'

  unauthenticated do
    #root "home#index"
    root :to => redirect("/users/sign_in")
  end

  authenticated :user do
    root 'messages#index', as: :authenticated_root
  end

  resources :messages
  post 'message', to: 'messages#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    validates :body, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :email, presence: true, length: { minimum: 3, maximum: 15 }, uniqueness: { case_sensitive: false}
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :first_name, :last_name, :email, :password)}
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :first_name, :last_name, :email, :password, :current_password)}
        end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_message, only: %i[ show edit update destroy ]
  #before_action :current_user, only: [:index, :show]

  # GET /messages or /messages.json
  def index
    @message = Message.new
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    # debugger
    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # def current_user
  #   #Check if current user matches message id
  #   @user = current_user.messages.find_by(id: params[:id])
  #   redirect_to messages_path, notice: "Not authorised" if @user.nil?
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      # params.fetch(:message, {})
      params.require(:message).permit(:body, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    debugger
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.6.0/font/bootstrap-icons.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

    <title>Messageme | Chatroom</title>
  </head>
  <body>
    <%= render 'messages/message_header' %>
    <div class="container">
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/messages/_chat.html.erb
<div class="chat-history">
    <ul class="m-b-0">
           <% @messages.each do |c| %>
                <!--<b><%=  %></b> : <%= c.body %>-->
               <%if c.user_id == current_user.id%> 
                    <li class="clearfix">
                        <div class="message-data text-right">
                            <span class="message-data-time text-right"><%= c.created_at %></span>
                            <!--<img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">-->
                        </div>
                        <div class="message other-message float-right"> <%= c.body %></div>
                    </li>
                <%else%>
                    
                    <li class="clearfix">
                        <div class="message-data">
                            <span class="message-data-time"><%= c.created_at %></span>
                        </div>
                        <div class="message my-message"><%= c.body %></div>                                    
                    </li>
                <%end%>
            <%end%>                              
        
    </ul>
</div>

app/views/messages/_contacts.html.erb
<ul class="list-unstyled chat-list mt-2 mb-0">
    <li class="clearfix">
        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" alt="avatar">
        <div class="about">
            <div class="name">Vincent Porter</div>
            <div class="status"> <i class="fa fa-circle offline"></i> left 7 mins ago </div>                                            
        </div>
    </li>
    <li class="clearfix active">
        <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
        <div class="about">
            <div class="name">Aiden Chavez</div>
            <div class="status"> <i class="fa fa-circle online"></i> online </div>
        </div>
    </li>
    <li class="clearfix">
        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
        <div class="about">
            <div class="name">Mike Thomas</div>
            <div class="status"> <i class="fa fa-circle online"></i> online </div>
        </div>
    </li>                                    
    <li class="clearfix">
        <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="avatar">
        <div class="about">
            <div class="name">Christian Kelly</div>
            <div class="status"> <i class="fa fa-circle offline"></i> left 10 hours ago </div>
        </div>
    </li>
    <li class="clearfix">
        <img src="https://bootdey.com/img/Content/avatar/avatar8.png" alt="avatar">
        <div class="about">
            <div class="name">Monica Ward</div>
            <div class="status"> <i class="fa fa-circle online"></i> online </div>
        </div>
    </li>
    <li class="clearfix">
        <img src="https://bootdey.com/img/Content/avatar/avatar3.png" alt="avatar">
        <div class="about">
            <div class="name">Dean Henry</div>
            <div class="status"> <i class="fa fa-circle offline"></i> offline since Oct 28 </div>
        </div>
    </li>
</ul>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><i class="bi bi-chat-quote-fill"></i> MessageMe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= link_to "message", messages_path, class:"nav-link" %>
        <%= link_to "Messages", root_path, class:"nav-link" %>
        <%= link_to "Login", new_user_session_path, class:"nav-link" %>
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </div>
    </div>
  </div>
</nav>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h2><i class="bi bi-people-fill"></i> | message</h2>

<div class="container">
<div class="row clearfix">
    <div class="col-lg-12">
        <div class="card chat-app">
            <div id="plist" class="people-list">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><i class="fa fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control" placeholder="Search...">
                </div>
                <%= render 'messages/contacts' %>
            </div>
            <div class="chat">
                <div class="chat-header clearfix">
                    <div class="row">
                        <div class="col-lg-6">
                            <a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
                                <img src="https://bootdey.com/img/Content/avatar/avatar2.png" alt="avatar">
                            </a>
                            <div class="chat-about">
                                <h6 class="m-b-0">Aiden Chavez</h6>
                                <small>Last seen: 2 hours ago</small>
                            </div>
                        </div>
                        <div class="col-lg-6 hidden-sm text-right">
                            <a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
                            <a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
                        </div>
                    </div>
                </div>
                <%= render 'messages/chat' %>
                <div class="chat-message clearfix">
                <%
=begin%>
 <%= form_with(model: @message, html: {class:""}, url: messages_path) do |form| %> 
<%
=end%>
                <%= form_with(model: @message, url: messages_path) do |form| %>
                    <div class="input-group mb-0">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fa fa-send"></i></span>
                        </div>
                        <%= form.text_field :body, class: "form-control", placeholder: "Enter message"%>
                        <%= form.number_field :user_id, id: :message_user_id, value: current_user.id, type: :hidden, class: "form-control", placeholder: "Enter message"%>
                        <!--<input type="text" class="form-control" placeholder="Enter text here...">-->
                    </div>
                    <%= form.submit%>
                <%end%>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/users-ext/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <p>
      <%= form.label :username %><br>
      <%= form.text_field :username, class:"form-control" %>
    </p>
    <p>
      <%= form.label :password %><br>
      <%= form.password_field :password, class:"form-control" %>
    </p>
  <div class="actions">
    <%= form.submit "Login", class:"btn btn-md btn-secondary"%>
  </div>
<% end %>

app/views/users-ext/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users-ext/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users-ext/new.html.erb
<div class="row">
<div class="col-md-4"></div>
<div class="col-md-4 justify-content-center">
<h1>Login</h1>
<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
</div>
<div class="col-md-4"></div>

</div>

app/views/users-ext/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>